### ISSUE TITLE
Local mode for rover roslaunch file

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#111]
Currently on startup the Odroid runs `rosRoverStart.sh` which calls `roslaunch rover.launch` amongst other things. This calls multiple server side scripts which would crash if run on the basestation since they depend on obscurities that only exist on the Odroid.
To make it easier for people to work locally a local roslaunch file should be created. The current services that don't have local modes should be modified to have them (not as command line arguments but as ros parameters).

- [ ] Change current local modes in server side scripts to use ros params instead of command line args (or both if no conflicts)
- - [ ] mux selector
- [ ] Add local modes to all other services that don't yet have it but would need it
- [ ] Create the local rover roslaunch file
- [ ] Test/verify local rover roslaunch file

Localize:
- [ ] ping acknowledgment
- [x] mux selector
- [ ] serial cmd
- [ ] task handler
- - [ ] RoverNode.py
- - [ ] ArmNode.py
- - [ ] start_ros_stream.sh
- - [ ] task_handler_server.py
- [ ] web video server?
- [ ] PDS node

Additional:
- [ ] Alias for switching between local/comp modes #221

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fully implement local mode software setup](https://trello.com/c/it68DGPN/121-fully-implement-local-mode-software-setup)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Local ROS Mode](https://trello.com/c/97eWSoDM/52-local-ros-mode)

**Comment by MartensCedric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Local Mode](https://trello.com/c/smULSKMJ/159-local-mode)
