### ISSUE TITLE
Improve the aesthetics of the front-end

### ISSUE THREAD

**Issue by MartensCedric** [space-concordia-robotics/robotics-prototype#137]
This issue serves to make the front-end of the rover pleasing to look at. 
- [x] Choosing a color palette (or adding nice ones after #115 )
- [x] The web elements (buttons, inputs etc) should be consistent and pleasant to look at
- [ ] All the pages should have good design for user experience

**Comment by MartensCedric** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve the aesthetics of the front-end](https://trello.com/c/muY0KArd/150-improve-the-aesthetics-of-the-front-end)

**Comment by MartensCedric** [comment]
keeping this open because its an epic. Even though we technically tagged the branch of #227 on this one when it should have been #153
