### ISSUE TITLE
[MCUA1] Users shall be able to control the arm manually (motor specific)

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#24]
MCUA1 = Micro Controller Unit Arm 1 

These use cases explain both automatic and manual modes. The last use case (switch controls to manual) all though technically belongs to issue #27, but is added here for clarification purposes.

Use cases:
- 4.1.6 Control claw motors
There are buttons on the GUI application to control the claw motors. The controls are pitch up/down, roll left/right, and claw open/close, or clockwise/counterclockwise for each respective motor depending on the control mode (automatic/manual). When the buttons are pressed a signal will be sent to the rover arm to make claw perform the requested action
- 4.1.7 Control arm motors
There are buttons on the GUI application to control the arm motors. The controls are arm up/down/left/right and arm back/forward, or clockwise/counterclockwise for each respective motor depending on the control mode (automatic/manual).. When the buttons are pressed a signal will be sent to the rover arm to make arm perform the requested action
- 4.1.8 Switch controls to manual
A mode of the controls in which the buttons allow the user to move each of the 6 motors respectively in either clockwise or counterclockwise direction.

## TODO checklist:
- [x] Control a single motor
- [x] Control multiple motors simultaneously
- [x] Open loop control: Attempt to attain a desired angle without angle feedback
- [ ] Closed loop control: Attain a desired angle using angle feedback and PID
- - [x] Implement PID control for motors with encoders
- - [ ] Determine correct gear ratios and multipliers for closed loop control (necessary for doing inverse kinematics properly but does not involve changing the structure of the code)
### Communications
- [ ] Settle on list of commands (in progress, this should be a separate issue for later)
- [x] Listen for a variety of commands and responds appropriately to them:
- - [x] Control motors: stop, move to angle, budge, home, reset angle value
- - [x] Adjust parameters: motor speed, arm speed, open loop gain, PID gains, gear ratio...
- - [x] Change modes: switch between open and closed loop, switch direction logic, software reboot
- - [ ] Enable or disable debugging (not sure if I want to do this anymore)
- [x] Validate commands to ensure that the inputs are correct
- [x] Respond to the inputs to execute the commands
- [ ] Implement ROSserial (in progress, this should be a separate issue for later)
- [ ] Make ROSserial work on Teensy (in progress, this should be a separate issue for later)
### Refined motor control
- [ ] Tune PIDs (fine-tuning can be put on hold as it works regardless)
- [ ] Implement speed profiles (not sure if I need to do this)
- [ ] Implement trajectory profiles (should this be on the Teensy or on the base station?)
- [ ] Automatically increase error based on position of arm joints in order to take arm weight into account
### Heartbeat
- [x] Blink in a specific pattern to indicate proper function
- [x] Blink in a specific pattern to indicate valid message is received
- [x] Blink in a specific pattern to indicate invalid message is received
### Varia
- [ ] Watchdog timer: reboot if an infinite loop occurs, freezing the microcontroller (to be integrated and tested)
- [ ] Save angles to memory when microcontroller is to be shut off and load them when microcontroller is turned back on
- [ ] Implement Teensy bootup sequence

**Comment by bnduwi** [comment]
@tatumalenko  I think you are working on this issue. When your ready you can use Zenhub (chrome extension) to move it to in progress.

**Comment by tatumalenko** [comment]
Damn it, forgot to append my commit messages with the issue number. Here they are:
04f0f43e2e2a08a70dd9803242b500da9ef3ece7
42e7637d699ed0b6c1f77d1641452556b5e86a42
8eb5088d8f94db9c6af69fef57d9f074d103b381
ae30d3d11b82491a0c8bfa73f62e2e746b52aef6
ae8ca0788a63264ab197ef363c281f116da1deab

**Comment by PeterGhimself** [comment]
Closing via #97 
A new issue will be created to document all the non-critical but still useful features not finished so far (and then linked here).
