### ISSUE TITLE
Localized testing of camera streams

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#244]
## Issue description
Currently the task handler only accepts the following parameters to run streams `/dev/ttyArmScienceCam`, `/dev/ttyFrontCam`, `/dev/ttyRearCam`, which is makes the code simple since it doesn't have to try to figure out which camera it's talking to now. This mapping is achieved by [this file](https://github.com/space-concordia-robotics/robotics-prototype/blob/master/robot/rover/config/my-webcams.rules) which is meant to be run on the odroid OBC.
There should be a way to run this part of the task handler in local mode so that developers could simulate that subsystem without the need to do any system configuration, just running the task handler in local mode like:
- `rosrun task_handler task_handler_server.py local`

## Task Breakdown
- [x] Allow for args to be any valid instance of `/dev/video*` for the computer on which task_handler_server.py runs on
- [x] Add 'local' parameter for server and client task handler scripts to switch between modes
- [ ] Run GIT for regression checks

**Comment by PeterGhimself** [comment]
I will address this on branch [simultaneous-streams-151](/space-concordia-robotics/robotics-prototype/tree/simultaneous-streams-151).

This should make all video streaming tasks easier to develop and test locally like for issues like #240
