### ISSUE TITLE
[EPIC] Arm Control

### ISSUE THREAD

**Issue by vexandmore** [space-concordia-robotics/robotics-prototype#634]
With new codebase for the CAN bus wheels, the arm control code needs to be rewritten. It is very messy right now, with a mix of code handling the logitech joystick, 3d mouse, and ps4 controller.
It will allow for the following control modes:

- Wheel control
- Arm control - forward kinematics (directly set each motor speed)
- Arm control - IK

Ideally it would support multiple controllers:

- Logitech joystick
- PS4 controller

This new code should be composed of the following parts:

- [ ] arm_control, wheel_control nodes which receive values for the arm and wheel motors and send them to the motors (#13 )
- [ ] absenc_node which receives absolute angle values and the control system to set motor angles in IK mode (#13)
- [ ] IKNode which performs IK calculations (#13)
- [ ] A joy_mapper node which listens to joystick messages and outputs to separate topics for different modes (#12 )
- [ ] New message types for joy_mapper (#11)
There are two other nice to haves:
- [ ] Using a PID as control system for motors (#16)

![image](https://github.com/space-concordia-robotics/robotics-orin/assets/44280158/50a83992-fd85-44f8-b7b3-41a3dc4dc65f)
