### ISSUE TITLE
[EPIC] Camera streams transmitting to GUI with AR detection

### ISSUE THREAD

**Issue by OZiad** [space-concordia-robotics/robotics-prototype#635]
# Short Description

This might already be completed by Nik but testing needs to be done. Keep in mind that we will probably need to have at least one camera publishing on the ROS network in order to detect AR tags ([See issue placeholder]()). 

# Acceptance Criteria

- [x] All cameras on the rover are live streaming on the GUI with minimal latency (vague for now, we'll have to see how it feels but lets aim for < 2 secs)
- [x] Camera streams work over radio without compromising quality
- [x]  Aruco Marker detection (#626 )
