### ISSUE TITLE
[EPIC] Rover autonomous navigation 

### ISSUE THREAD

**Issue by OZiad** [space-concordia-robotics/robotics-prototype#637]
# Short Description

We  are using the [Nav2](https://navigation.ros.org/getting_started/index.html) library to implement autonomy for the rover. We have URDF files describing the rover ([robot_description](https://github.com/space-concordia-robotics/robotics-orin/blob/9ad04fc1cf2ef7fce3b08ab782fe6b912a5ab26b/src/beep_autonomy/src/description/rover_description.urdf)) which Nav2 relies on for its transforms (see: tf2).

Mathieu is currently working on doccumenting some of the issues with the Lidar.

# Acceptance Criteria

- [ ] Fix Lidar connection issues (#25)
- [ ] GPS publishing (#2)
- [ ] Autonomous path planning to a GPS coordinate using Lidar
- [ ] ZED2 integrated into Nav2 system with working depth perception

# Useful links

* [Lidar installation script(might have issues with the port)](https://github.com/space-concordia-robotics/robotics-orin/blob/main/scripts/lidar_setup.sh)
* [ZED2 + ROS2](https://www.stereolabs.com/docs/ros2)
