### ISSUE TITLE
[EPIC] Integrate ROS web GUI to monitor and control the rover

### ISSUE THREAD

**Issue by OZiad** [space-concordia-robotics/robotics-prototype#638]
# Short Description

Niko has built a web GUI in angular, we need to add missing features and test the camera streams.

# Acceptance Criteria

- [x] Cameras streams are clearly visible over local network/radio
- [ ] Rover GPS location can be accurately tracked on GUI
- [ ] Arm visualisation + error feedback
- [ ] Science carousel stuff (Spec software +TBD)
- [ ] Autonomy Commands/Status integration
