### ISSUE TITLE
[EPIC] Poll GPS for coordinates and publish data on ROS network

### ISSUE THREAD

**Issue by OZiad** [space-concordia-robotics/robotics-prototype#641]
## Short Description

We are rewriting the low level code for the GPS that will be used to poll the device by GpsPublisherNode. The GPS communicates over I2C using Ubx packets. We will be implementing a system that allows us to serialize and deserialize Ubx packets in C++ (with Josh's help). These packets will be used by send and receive data from the GPS. 

note: In the future we can hopefully communicate over I2C using a wrapper object as without needing to interact with low level C code or manually reading bytes.

## Acceptance Criteria

- [ ] We can send and receive UBX packets over I2C.
- [ ] We are able to poll the GPS at a frequency of 1Hz for coordinates and translate it to meaningful data.
- [ ] GPS data received is published to a ROS topic every. #629
