### ISSUE TITLE
Science page

### ISSUE THREAD

**Issue by PeterGhimself** [space-concordia-robotics/robotics-prototype#86]
# TODO:
- [x] Rosify GUI to send messages to and receive feedback from the science payload MCU
- - [x] Initial configuration for states of UI components
- - [x] Actuation commands linked to control input of MCU
- - - [x] Drill
- - - - [x] Change direction CW/CCW
- - - - [x] Max speed go
- - - - [x] Speed set go
- - - - [x] Time set go
- - - - [x] Speed + time set go
- - - - [x] RPM feedback
- - - [x] Elevator
- - - - [x] Change direction UP/DOWN
- - - - [x] Max speed go
- - - - [x] Feed set go
- - - - [x] Distance (max feed) set go
- - - - [x] Distance + feed set go
- - - - [x] Feed feedback (%)
- - - - [x] Limit switches
- - - [x] Turntable
- - - - [x] Change # of pizza slices to 4 in UI
- - - - [x] Limit switches
- - - - [x] Rotate L/R by 90 degrees
- - - - [ ] ~~Rotate to index~~
- - - - [x] Turntable position feedback
- - [x] Add toggle buttons for video streams
- [x] Test and possibly port firmware to teensy if changes are necessary
- [x] Integration test
- [ ] Templatify front end

Wireframe:

![drill_science_page](https://user-images.githubusercontent.com/19865282/52883089-c0da3900-3137-11e9-88f0-4f2124f2fdea.PNG)

**Comment by bnduwi** [comment]
First draft visual layout
![image](https://user-images.githubusercontent.com/32171245/57665062-7c402b80-75c8-11e9-8d47-3378a48ffb8a.png)

**Comment by PeterGhimself** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test Drill Controls](https://trello.com/c/F2CF07CD/82-test-drill-controls)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test turntable through GUI](https://trello.com/c/Yo3vsijE/83-test-turntable-through-gui)

**Comment by vashmata** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Link Turntable to GUI](https://trello.com/c/1618zHa5/6-link-turntable-to-gui)
